/**
 * Storage key (path) helpers for DigitalOcean Spaces.
 *
 * Folder layout and lifecycle policies (configured via S3 lifecycle rules):
 *
 *   tmp/           Temporary — files in transit during upload chunks/transfer.
 *                  Auto-deleted after 7 days.
 *
 *   processing/    Reserved for future use (e.g. transcoding jobs).
 *                  Auto-deleted after 7 days. NOT used in Phase 1.
 *
 *   request_mat/   Confirmed raw uploads from requesters (images & videos).
 *                  Auto-deleted after 90 days.
 *
 *   thumbnails/    Preview images for uploaded materials and final clips.
 *                  Retained for 5 years.
 *
 *   clips/         Final produced and published clip videos.
 *                  Retained for 8 years.
 *
 * Subfolder convention (all folders):
 *   {folder}/{userId}/{YYYY-MM-DD}/{requestId}/{uuid}-{sanitizedFilename}
 *
 * The date segment uses the server's current UTC date at the time the key is
 * generated. This makes objects browseable by date without a DB query.
 */

function utcDateSegment(): string {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_");
}

function uuid(): string {
  return crypto.randomUUID();
}

/**
 * Key for a file being uploaded — stored in tmp/ until confirmed.
 * Lifecycle: auto-deleted after 7 days.
 */
export function buildTmpKey(
  userId: string,
  requestId: string,
  fileName: string
): string {
  return `tmp/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(fileName)}`;
}

/**
 * Key for a confirmed raw upload — moved here from tmp/ on upload confirmation.
 * Lifecycle: auto-deleted after 90 days.
 */
export function buildRequestMatKey(
  userId: string,
  requestId: string,
  fileName: string
): string {
  return `request_mat/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(fileName)}`;
}

/**
 * Key for a thumbnail image.
 * Used for:
 *   - Preview thumbnails of uploaded images and videos (generated on confirmation).
 *   - Preview thumbnails of the final produced clip (generated by staff/system).
 * Lifecycle: retained for 5 years.
 *
 * @param baseName  Filename without extension (e.g. "my_video" from "my_video.mp4").
 */
export function buildThumbnailKey(
  userId: string,
  requestId: string,
  baseName: string
): string {
  return `thumbnails/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(baseName)}.jpg`;
}

/**
 * Key for a final produced clip video.
 * Used for:
 *   - The delivered output clip uploaded by staff after production.
 *   - The published version once delivered to the platform/client.
 * Lifecycle: retained for 8 years.
 */
export function buildClipKey(
  userId: string,
  requestId: string,
  fileName: string
): string {
  return `clips/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(fileName)}`;
}
