/**
 * Storage key (path) helpers for DigitalOcean Spaces.
 *
 * Folder layout. Primary deletion is APP-DRIVEN (scripts/retention-sweep.js +
 * StorageLifecycleService purge at Delivered+7d / 30d inactivity — see
 * docs/storage-lifecycle-design.md Addendum A). The S3 lifecycle rules listed
 * below are only age-based BACKSTOPS for objects the app path missed.
 *
 *   tmp/           In-transit presigned uploads (deleted on confirm). Backstop: 1 day.
 *   processing/    Reserved, unused.                                 Backstop: 1 day.
 *   request_mat/   Confirmed raw uploads (images & videos).          Backstop: 30 days.
 *   thumbnails/    Previews of uploads and final clips (kept for
 *                  request-history UI; exempt from app purge).       Backstop: 730 days.
 *   clips/         Legacy final-clip prefix (no live writers).       Backstop: 60 days.
 *   ai_videos/, animated_videos/, animated_overlays/,
 *   processed_audio/, voice_recordings/                              Backstop: 30 days.
 *   final_exports/, preview_exports/                                 Backstop: 60 days.
 *
 * The full prefix list lives in src/config/mediaPrefixes.json — when adding a
 * prefix here, add it there AND add a bucket lifecycle backstop rule.
 *
 * Subfolder convention (all folders):
 *   {folder}/{userId}/{YYYY-MM-DD}/{requestId}/{uuid}-{sanitizedFilename}
 *
 * The date segment uses the server's current UTC date at the time the key is
 * generated. This makes objects browseable by date without a DB query.
 */

function utcDateSegment(): string {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_");
}

function uuid(): string {
  return crypto.randomUUID();
}

/**
 * Key for a file being uploaded — stored in tmp/ until confirmed.
 * Lifecycle: deleted on upload confirmation; 1-day backstop.
 */
export function buildTmpKey(
  userId: string,
  requestId: string,
  fileName: string
): string {
  return `tmp/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(fileName)}`;
}

/**
 * Key for a confirmed raw upload — moved here from tmp/ on upload confirmation.
 * Lifecycle: purged at Delivered+7d or 30d inactivity; 30-day backstop.
 */
export function buildRequestMatKey(
  userId: string,
  requestId: string,
  fileName: string
): string {
  return `request_mat/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(fileName)}`;
}

/**
 * Key for a thumbnail image.
 * Used for:
 *   - Preview thumbnails of uploaded images and videos (generated on confirmation).
 *   - Preview thumbnails of the final produced clip (generated by staff/system).
 * Lifecycle: exempt from app purge (request-history UI); 730-day backstop.
 *
 * @param baseName  Filename without extension (e.g. "my_video" from "my_video.mp4").
 */
export function buildThumbnailKey(
  userId: string,
  requestId: string,
  baseName: string
): string {
  return `thumbnails/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(baseName)}.jpg`;
}

/**
 * Key for a final produced clip video.
 * Used for:
 *   - The delivered output clip uploaded by staff after production.
 *   - The published version once delivered to the platform/client.
 * Lifecycle: legacy prefix (no live writers); purged with request; 60-day backstop.
 */
export function buildClipKey(
  userId: string,
  requestId: string,
  fileName: string
): string {
  return `clips/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(fileName)}`;
}

// ── AI Pipeline storage keys ────────────────────────────────────────────────
// Separate folders with distinct lifecycle policies for each pipeline stage.

/**
 * Key for an AI-generated base video — cumulative scene output.
 * Lifecycle: purged with request; 30-day backstop.
 */
export function buildAiVideoKey(userId: string, requestId: string): string {
  return `ai_videos/${userId}/${utcDateSegment()}/${requestId}/${uuid()}.mp4`;
}

/**
 * Key for a staff voice recording (RVC-converted in browser before upload).
 * Lifecycle: purged with request; 30-day backstop.
 */
export function buildVoiceRecordingKey(
  userId: string,
  requestId: string,
  fileName: string
): string {
  return `voice_recordings/${userId}/${utcDateSegment()}/${requestId}/${uuid()}-${sanitize(fileName)}`;
}

/**
 * Key for the processed voice audio (kept for legacy; not written by RVC flow).
 * Lifecycle: purged with request; 30-day backstop.
 */
export function buildProcessedVoiceKey(userId: string, requestId: string): string {
  return `processed_audio/${userId}/${utcDateSegment()}/${requestId}/${uuid()}.mp3`;
}

/**
 * Key for an FFmpeg-animated video (base video + graphic overlays, before final composition).
 * Lifecycle: purged with request; 30-day backstop.
 */
export function buildAnimatedVideoKey(userId: string, requestId: string): string {
  return `animated_videos/${userId}/${utcDateSegment()}/${requestId}/${uuid()}.mp4`;
}

/**
 * Key for a Remotion-rendered transparent overlay clip (captions +
 * lower-thirds) for one aspect ratio (Phase 4 — animation/Remotion step).
 * Stored as `.webm` (VP9 + alpha) so FFmpeg can overlay it onto the base
 * video with `overlay=format=auto`.
 * Lifecycle: purged with request; 30-day backstop.
 */
export function buildAnimatedOverlayKey(
  userId: string,
  requestId: string,
  ratio: "9:16" | "16:9" | "1:1" | "4:5"
): string {
  const safeRatio = ratio.replace(":", "-");
  return `animated_overlays/${userId}/${utcDateSegment()}/${requestId}/${safeRatio}/${uuid()}.webm`;
}

/**
 * Key for a final FFmpeg-exported clip in a specific aspect ratio.
 * Lifecycle: purged at Delivered+7d; 60-day backstop.
 *
 * @param ratio  e.g. "9-16", "16-9", "1-1", "4-5" (slashes replaced with dashes for path safety),
 *               or "tvent" for the dedicated Tvent App export.
 */
export function buildFinalClipKey(
  userId: string,
  requestId: string,
  ratio: "9:16" | "16:9" | "1:1" | "4:5" | "tvent"
): string {
  const safeRatio = ratio.replace(":", "-");
  return `final_exports/${userId}/${utcDateSegment()}/${requestId}/${safeRatio}/${uuid()}.mp4`;
}

/**
 * Key for a watermarked ("RClipper" tiled overlay) preview clip — the pre-rendered
 * sibling of a final export, shown to a requester whose download is still locked
 * (unpaid). Stored under its own `preview_exports/` prefix so the storage
 * lifecycle can treat previews independently of the clean masters (they are
 * disposable once the download is unlocked).
 * Lifecycle: purged with request; 60-day backstop (expire-preview-exports-60d).
 *
 * @param ratio  "9:16" | "16:9" | "1:1" | "4:5" or "tvent" for the Tvent export.
 */
export function buildWatermarkedPreviewKey(
  userId: string,
  requestId: string,
  ratio: "9:16" | "16:9" | "1:1" | "4:5" | "tvent"
): string {
  const safeRatio = ratio.replace(":", "-");
  return `preview_exports/${userId}/${utcDateSegment()}/${requestId}/${safeRatio}/${uuid()}.mp4`;
}
