import { VideoGenerationJobStatus } from "@/domain/enums/VideoGenerationJobStatus";
import { VideoGenerationStep } from "@/domain/enums/VideoGenerationStep";

/**
 * Represents one AI video production pipeline run attached to a ClipRequest.
 *
 * One job exists per production run. If a request goes back and forth through
 * pipeline steps the same job record is updated in place.
 *
 * TODO: PostgreSQL — map to `video_generation_jobs` table.
 */
export interface VideoGenerationJob {
  id: string;
  requestId: string;

  status: VideoGenerationJobStatus;
  currentStep: VideoGenerationStep;

  // ── Step 1: ChatGPT Vision outputs ─────────────────────────────────────────
  /** JSON-serialised ScenePlan[] generated by ChatGPT. */
  scenePlan: string | null;
  /** Thai voiceover script (~40-50 words, ~15s at natural pace). */
  scriptThai: string | null;
  /** English translation of scriptThai — used as subtitle overlay. */
  scriptEnglish: string | null;
  /** First-3-second attention hook in Thai. */
  hookThai: string | null;
  /** First-3-second attention hook in English. */
  hookEnglish: string | null;
  /** Platform post caption — Thai. */
  captionThai: string | null;
  /** Platform post caption — English. */
  captionEnglish: string | null;
  /** Platform post caption — Simplified Chinese. */
  captionChinese: string | null;

  // Staff-approved versions (may differ from generated if staff edited them)
  approvedScenePlan: string | null;
  approvedScriptThai: string | null;
  approvedScriptEnglish: string | null;
  approvedHookThai: string | null;
  approvedHookEnglish: string | null;
  approvedCaptionThai: string | null;
  approvedCaptionEnglish: string | null;
  approvedCaptionChinese: string | null;

  // ── Step 2: Kling AI ────────────────────────────────────────────────────────
  /** Kling async task ID for polling until video is ready. */
  klingTaskId: string | null;
  /** Kling's last reported task sub-status ("submitted" = queued, "processing" = rendering). */
  klingStatus: "submitted" | "processing" | null;
  /** Timestamp of the last successful Kling status poll. */
  klingLastPolledAt: Date | null;
  /** UploadedAsset ID of the AI-generated base video. */
  baseVideoAssetId: string | null;

  // ── Step 3: Voice ───────────────────────────────────────────────────────────
  /** RVC voice model name used for conversion on the Mac Mini server. */
  rvcVoiceModel: string;
  /** UploadedAsset ID of the staff's raw voice recording. */
  voiceRecordingAssetId: string | null;
  /** UploadedAsset ID of the RVC-converted audio (same asset as voiceRecordingAssetId — conversion happens in browser). */
  processedVoiceAssetId: string | null;

  // ── Step 4: Final exports (UploadedAsset IDs per ratio) ─────────────────────
  finalExport_9_16_assetId: string | null;
  finalExport_16_9_assetId: string | null;
  finalExport_1_1_assetId: string | null;
  finalExport_4_5_assetId: string | null;

  // ── Failure tracking ────────────────────────────────────────────────────────
  /** Which step was running when the pipeline entered Failed state. Used to retry from that step. */
  failedAtStep: VideoGenerationStep | null;

  // ── Staff approval tracking ─────────────────────────────────────────────────
  contentApprovedBy: string | null;
  videoApprovedBy: string | null;
  voiceApprovedBy: string | null;
  finalApprovedBy: string | null;

  createdAt: Date;
  updatedAt: Date;
}

export type CreateVideoGenerationJobInput = Omit<
  VideoGenerationJob,
  "id" | "createdAt" | "updatedAt"
>;

export type UpdateVideoGenerationJobInput = Partial<
  Omit<VideoGenerationJob, "id" | "requestId" | "createdAt" | "updatedAt">
>;

/** Parsed representation of a single scene in the ChatGPT scene plan. */
export interface ScenePlan {
  sceneNumber: number;
  durationSeconds: number;
  visualDescriptionThai: string;
  imageIndexes: number[];
  /** @deprecated AI no longer generates this; kept for seed/legacy data compat. */
  visualDescription?: string;
  /** @deprecated AI no longer generates this; kept for seed/legacy data compat. */
  motionNotes?: string;
  /** @deprecated AI no longer generates this; kept for seed/legacy data compat. */
  motionNotesThai?: string;
}
